/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'https://www.checklyhq.com/',
      instruction:
        'Click on the Resources dropdown menu, then click into to the developer docs option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am clicking the Resources dropdown menu to begin accessing the developer docs option as required by the objective.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
            {
              failover: [
                "(.//button[normalize-space(.)='Resources'])[1]",
                'nav.container > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
              ],
            },
          )
          .click();

        // I am clicking the developer documentation option in the Resources dropdown to open the developer docs as required by the objective.
        await page
          .find(".//a[normalize-space(.)='Documentation']", {
            failover: [
              "li:nth-of-type(1) > [href='/docs/']",
              'div:nth-of-type(1) > ul > li:nth-of-type(1) > a.text-base',
            ],
          })
          .click();

        // I have opened the Resources dropdown and navigated into the Documentation link, which is the developer docs option requested in the objective.
        await page.run('markObjectiveComplete', {
          details:
            'Clicked the Resources menu on https://www.checklyhq.com/, then selected the Documentation link under the Developers section, arriving at https://www.checklyhq.com/docs/ (Checkly Documentation).',
        });
      },
    },
    {
      pageUrl: 'https://www.checklyhq.com/docs/',
      instruction:
        'Do a search for "Playwright check suite" and chose the match for "Constructs > DETECT".',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am starting a search for Playwright check suite within the documentation to work towards the Constructs > DETECT page.
        await page
          .find(".//a[normalize-space(.)='Constructs']", {
            failover: [
              "div:nth-of-type(2) > div > [href='/docs/constructs/overview']",
              'div.nav-tabs > a:nth-of-type(2)',
            ],
          })
          .click();

        // I am navigating to the Playwright check suite documentation under Constructs to find the DETECT section.
        await page
          .find(".//a[normalize-space(.)='Playwright Check Suites']", {
            failover: [
              "[href='/docs/constructs/playwright-check']",
              'li:nth-of-type(8) > a.group',
            ],
          })
          .click();

        // I have navigated to the Playwright Check Suite page under Constructs > DETECT as requested.
        await page.run('markObjectiveComplete', {
          details:
            'Opened the Checkly documentation, selected Constructs, then under the DETECT section chose Playwright Check Suites, landing on https://www.checklyhq.com/docs/constructs/playwright-check/ which is the Playwright Check Suite page under Constructs > DETECT.',
        });
      },
    },
    {
      pageUrl: 'https://unstable-survey-dinoer.replit.app/',
      instruction:
        'Fill out the all of the survey questions with fake data go through\nthe submission process until you get to a "Thank You" page.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          surveyData: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                question: { type: 'string' },
                response: { type: 'string' },
              },
              required: ['question', 'response'],
              additionalProperties: false,
            },
          },
        },
        required: ['surveyData'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am setting autonomous control so I can navigate the survey and submit it through all steps until the Thank You page.
        await page.run('setRunMode', {
          runMode: 'AUTONOMOUS',
        });

        // I am entering a fake name to start filling out the survey so I can eventually submit it and reach the Thank You page.
        await page
          .find('#\\:rj\\:-form-item', {
            failover: [
              ".//label[normalize-space()='Your Name *']/following-sibling::input",
              "[name='name']",
            ],
          })
          .inputText('Alexandra Testington');

        // I am entering a fake but plausible email so the survey can be submitted successfully.
        await page
          .find('#\\:rk\\:-form-item', {
            failover: [
              ".//label[normalize-space()='Contact Email *']/following-sibling::input",
              "[name='email']",
            ],
          })
          .inputRandomizedEmailAddress('example@testmail.com');

        // I am selecting an occupation so that all required fields on the first survey step are completed and I can proceed toward the Thank You page.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click();

        // I am toggling one interest checkbox to satisfy the required 'What interests you?' field so the survey can be submitted.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(2) > div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click();

        // I am scrolling down to reveal the rest of the survey form including navigation controls needed to advance toward the Thank You page.
        await page.find('html').scroll('DOWN');

        // I am advancing to the next step of the survey so I can eventually reach the Thank You page after submitting all answers.
        await page
          .find(".//button[normalize-space(.)='Next']", {
            failover: ['button.inline-flex', 'div.mt-8 > button'],
          })
          .click();

        // I am opening the occupation dropdown so I can select a fake job and complete the required field to progress toward the Thank You page.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click();

        // I am selecting at least one interest so the required interests field is satisfied and I can move on through the survey toward the Thank You page.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(2) > div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click();

        // I am opening the occupation dropdown so I can choose a fake occupation and complete this required survey field to move toward the Thank You page.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click();

        // I am selecting at least one interest so the required interests question is satisfied and I can advance through the survey toward the Thank You page.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(2) > div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click();

        // I am opening the occupation dropdown so I can choose a fake occupation and complete the required field to progress the survey toward the Thank You page.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click();

        // I am selecting Technology as an interest so the required interests field is satisfied and I can advance toward the Thank You page.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(2) > div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click();

        // I am opening the occupation dropdown so I can select a fake occupation and complete this required field to progress the survey toward the Thank You page.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click();

        // I am selecting Technology as an interest so the required interests question is satisfied and I can move toward submitting the survey and reaching the Thank You page.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(2) > div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click();

        // I am opening the occupation dropdown so I can pick a fake occupation and complete this required field to move the survey toward the Thank You page.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click();

        // I am selecting a fake occupation option so the required occupation field is completed and I can move forward in the survey toward the Thank You page.
        await page
          .find('#radix-\\:rm\\: > div > div:nth-of-type(2)', {
            failover: [
              ".//div[normalize-space(.)='Employed']",
              "[role='presentation'] > div:nth-of-type(2)",
            ],
          })
          .click();

        // I am selecting at least one interest so the required 'What interests you?' field is completed and I can proceed through the survey toward the Thank You page.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click();

        // I am scrolling down to reveal the Next or Continue button so I can proceed to the next step of the survey toward the Thank You page.
        await page.find('html').scroll('DOWN');

        // I am advancing to the next step of the survey so I can continue filling it out and eventually reach the Thank You page.
        await page
          .find(".//button[normalize-space(.)='Next']", {
            failover: ['button.inline-flex', 'div.mt-8 > button'],
          })
          .click();

        // I am submitting the completed survey so I can reach the final Thank You page and complete the overall objective.
        await page
          .find(".//button[normalize-space(.)='Submit']", {
            failover: [
              'div.mt-8 > button:nth-of-type(2)',
              'div.bg-white > div:nth-of-type(2) > button:nth-of-type(2)',
            ],
          })
          .click();

        // I am marking the objective complete because the survey has been submitted and the Thank You page is displayed.
        await page.run('markObjectiveComplete', {
          details:
            'Filled the survey with fake data (name, randomized email, occupation, interest, no comments), navigated through all steps, clicked Submit on the selection review page, and reached the Thank You page at /thank-you.',
        });
      },
    },
    {
      pageUrl: 'https://en.wikipedia.org/wiki/Software_testing',
      instruction:
        'View the page history, sort by oldest, and find the oldest revision date (the history page displays in "time, day month year format").',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          day: { type: 'number' },
          month: { type: 'number' },
          year: { type: 'number' },
        },
        required: ['day', 'month', 'year'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am clicking the View history tab to open the page history so I can later sort it by oldest and find the oldest revision date.
        await page
          .find("(.//a[normalize-space(.)='View history'])[1]", {
            failover: [
              "[title='Past revisions of this page [ctrl-option-h]']",
              "nav:nth-of-type(1) > div > div > ul > li:nth-of-type(3) > [href='/w/index.php?title=Software_testing&action=history']",
            ],
          })
          .click();

        // I am clicking the oldest link to sort the page history by oldest revisions so I can later find the oldest revision date.
        await page
          .find("(.//a[normalize-space(.)='oldest'])[1]", {
            failover: [
              "div:nth-of-type(3) > [href='/w/index.php?title=Software_testing&action=history&dir=prev']",
              'div:nth-of-type(3) > a.mw-lastlink',
            ],
          })
          .click();

        // I am marking the objective complete because the page history is now sorted by oldest and I have identified the oldest revision date.
        await page.run('markObjectiveComplete', {
          details:
            "On the Software testing revision history page, after clicking the 'oldest' link, the earliest listed revision is dated 19:35, 13 January 2004 (time, day month year format). This is the oldest revision date shown.",
        });
      },
    },
    {
      pageUrl: 'https://news.ycombinator.com/',
      instruction:
        'Scroll to the bottom of the page, locate search input field, do a search with keyword "mac app for web testing"',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am scrolling down the main page so that I can reach the bottom to look for the search input field and perform the required search.
        await page
          .find('html > body', { failover: ['body'] })
          .scroll('DOWN', { maxScroll: true });

        // I am entering the requested search term into the search input at the bottom of the page to perform the required search.
        await page
          .find(
            '#hnmain > tbody > tr:nth-of-type(4) > td > center > form > input',
            { failover: ["[name='q']", 'form > input'] },
          )
          .inputText('mac app for web testing', { submit: true });

        // I have scrolled to the bottom of the page, located the search input field, and performed a search with the keyword 'mac app for web testing', fulfilling the overall objective.
        await page.run('markObjectiveComplete', {
          details:
            "Reached the bottom of the Hacker News front page, identified the search box labeled 'Search:', entered the query 'mac app for web testing', submitted it, and the browser is now displaying the HN Algolia search results for that query.",
        });
      },
    },
    {
      pageUrl: 'https://www.donobu.com/',
      instruction:
        'Scan the page for any responsiveness issues (overlap, misalignment, broken layout, clipping, bad spacing, resizing problems, or horizontal scroll). \n        Return PASS only if everything looks correct.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          status: { type: 'string', enum: ['PASS', 'FAIL'] },
          issues: { type: 'array', items: { type: 'string' } },
        },
        required: ['status', 'issues'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am scrolling the main page to inspect additional content for any responsiveness or layout issues before determining pass or fail.
        await page
          .find('html.bg-background', { failover: ['html'] })
          .scroll('DOWN');

        // I have visually inspected the current viewport for overlap, misalignment, clipping, spacing problems, resizing issues, or horizontal scroll and found none.
        await page.run('markObjectiveComplete', {
          details:
            'PASS. The hero section, navigation (logo, menu button, Download button), primary CTA, and example app screenshots all appear well-aligned and properly spaced on this mobile viewport. No overlapping elements, clipped content, or unexpected horizontal scrolling are visible in this view.',
        });
      },
    },
    {
      pageUrl: 'https://briefcase.chat/',
      instruction:
        'Evaluate this chatbot for topic compliance.\n     - Ask a few legal-related questions and confirm the bot responds appropriately.\n     - Ask a few unrelated / off-topic questions and confirm the bot refuses or stays on-topic.\n    ',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          status: { type: 'string', enum: ['PASS', 'FAIL'] },
          issues: { type: 'array', items: { type: 'string' } },
        },
        required: ['status', 'issues'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am entering a name so I can start a chat and evaluate the chatbot for topic compliance.
        await page
          .find('#name', {
            failover: [
              ".//label[normalize-space()='Name']/following-sibling::input",
              "[placeholder='Enter your name']",
            ],
          })
          .inputText('Tester');

        // I am starting the chat so I can ask questions and evaluate the chatbot for topic compliance.
        await page
          .find(".//button[normalize-space(.)='Start Chatting']", {
            failover: [
              'div:nth-of-type(2) > div:nth-of-type(2) > button.inline-flex',
              'div.space-y-4 > div:nth-of-type(2) > button',
            ],
          })
          .click();

        // I am asking a substantive legal-related question so I can evaluate whether the chatbot responds appropriately on-topic.
        await page
          .find("[placeholder='Type your message...']", {
            failover: ['input.flex', 'form.flex > div > input:nth-of-type(1)'],
          })
          .inputText(
            'I am a startup founder in Delaware. Can you explain the key differences between granting stock options and granting restricted stock to early employees, including typical tax and vesting implications?',
          );

        // I am sending the first legal-related question to the chatbot so I can evaluate its topic compliance.
        await page
          .find('form.flex > div > button:nth-of-type(2)', {
            failover: [
              'body.bg-background > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(3) > div > form > div > button:nth-of-type(2)',
              'body > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(3) > div > form > div > button:nth-of-type(2)',
            ],
          })
          .click();

        // I am waiting briefly to allow the chatbot time to generate a response so I can evaluate its topic compliance.
        await page.waitForTimeout(5000);

        // I am asking a second, unrelated off-topic question to test whether the legal-focused chatbot refuses or redirects to the legal topic.
        await page
          .find("[placeholder='Type your message...']", {
            failover: ['input.flex', 'form.flex > div > input:nth-of-type(1)'],
          })
          .inputText(
            'Can you give me a detailed workout plan to build muscle and lose fat over the next 12 weeks?',
            { submit: true },
          );

        // I am waiting briefly to allow the chatbot to respond to the off-topic fitness question so I can evaluate whether it stays on legal topics.
        await page.waitForTimeout(5000);

        // I am marking the objective complete because I have tested both legal-related and off-topic questions and observed the chatbot’s topic compliance behavior.
        await page.run('markObjectiveComplete', {
          details:
            'I asked the Briefcase chatbot a detailed legal question about stock options versus restricted stock for a Delaware startup and it provided an on-topic legal explanation discussing tax and vesting implications. I then asked an off-topic question requesting a detailed workout plan. The chatbot correctly refused to provide fitness advice and clarified that it is limited to legal information for startups and investments, inviting further legal questions. Based on these interactions, the chatbot behaves as expected for topic compliance: it answers relevant legal questions and declines unrelated ones while redirecting back to its legal domain.',
        });
      },
    },
    {
      pageUrl: 'https://www.starbucks.com/',
      instruction: 'Go to the featured menu page',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am clicking the menu navigation link to start navigating to the featured menu page, which is under the menu section.
        await page
          .find("(.//a[normalize-space(.)='Menu'])[1]", {
            failover: [
              "div:nth-of-type(2) > div:nth-of-type(1) > ul > li:nth-of-type(1) > [href='/menu']",
              'li:nth-of-type(1) > a.sb-globalNav__desktopLink',
            ],
          })
          .click();

        // I am confirming that I have successfully navigated to the menu section as a prerequisite to locating the featured menu page.
        await expect(page).toHaveURL('https://www.starbucks.com/menu');

        // I am clicking the Featured sub-navigation link to navigate from the general menu to the featured menu page, fulfilling the objective.
        await page
          .find(".//a[normalize-space(.)='Featured']", {
            failover: [
              "[href='https://www.starbucks.com/menu/featured']",
              'li:nth-of-type(2) > a.sb-global-subnav-item',
            ],
          })
          .click();

        // I have successfully navigated to the featured menu page as requested in the overall objective.
        await page.run('markObjectiveComplete', {
          details:
            'The browser is now on https://www.starbucks.com/menu/featured/, which is the Starbucks featured menu page displaying highlighted seasonal and featured items.',
        });
      },
    },
    {
      pageUrl: 'https://www.starbucks.com/menu/featured/',
      instruction: 'Find a Starbucks store in Stowe, Vermont',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am clicking the Find a store link to start locating a Starbucks store in Stowe, Vermont.
        await page
          .find("(.//a[normalize-space(.)='Find a store'])[1]", {
            failover: [
              "span:nth-of-type(1) > [href='/store-locator']",
              'span:nth-of-type(1) > a.sb-textLink',
            ],
          })
          .click();

        // I am waiting briefly to allow the Starbucks store locator page to finish loading so that I can search for a Starbucks in Stowe, Vermont.
        await page.waitForTimeout(3000);

        // I am entering Stowe, Vermont into the Starbucks store locator search box to find a Starbucks store in Stowe, Vermont.
        await page
          .find(
            "[aria-label='Enter a location to search for Starbucks stores']",
            { failover: ["[name='place']", "[placeholder='Find a store']"] },
          )
          .inputText('Stowe, Vermont', { submit: true });

        // I am submitting the search for Stowe, Vermont to load the list of nearby Starbucks stores and identify one located in or closest to Stowe, Vermont.
        await page
          .find("[aria-label='Submit search term']", {
            failover: [
              "[data-e2e='submitSearchTermButton']",
              'button.button___s0b6x',
            ],
          })
          .click();

        // I have located a Starbucks store in Stowe, Vermont using the Starbucks store locator.
        await page.run('markObjectiveComplete', {
          details:
            'Starbucks store found in Stowe, Vermont: Stowe, 109 Main Street, 109 Main St, Stowe. The locator shows it as 0.1 miles away from the searched location, currently closed, opening Tuesday at 5:00 AM, with in-store service available.',
        });
      },
    },
    {
      pageUrl: 'https://en.wikipedia.org/wiki/Software_testing',
      instruction:
        'View the page history, sort by oldest, and find the earliest (oldest) revision shown in the list (the history page displays in "time, day month year format").',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          day: { type: 'number' },
          month: { type: 'number' },
          year: { type: 'number' },
        },
        required: ['day', 'month', 'year'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the Wikipedia logo to navigate to the main page, from where I can access the page history or navigation options to view the history of the Software testing page.
        await page
          .find("div:nth-of-type(1) > [href='/wiki/Main_Page']", {
            failover: ['a.mw-logo', 'div.vector-header-start > a'],
          })
          .click();

        // Navigating back to the Software testing page so I can access its page history to view the revisions and find the oldest one.
        await page.goto('https://en.wikipedia.org/wiki/Software_testing');

        // Clicking on the "View history" link to access the page history where I can view all revisions and sort them by oldest to find the earliest revision.
        await page
          .find("(.//a[normalize-space(.)='View history'])[1]", {
            failover: [
              "[title='Past revisions of this page [alt-h]']",
              "nav:nth-of-type(1) > div > div > ul > li:nth-of-type(3) > [href='/w/index.php?title=Software_testing&action=history']",
            ],
          })
          .click();

        // Clicking on the "oldest" link to navigate to the oldest revisions of the Software testing page, which will allow me to find the earliest revision in the history.
        await page
          .find("(.//a[normalize-space(.)='oldest'])[1]", {
            failover: [
              "div:nth-of-type(3) > [href='/w/index.php?title=Software_testing&action=history&dir=prev']",
              'div:nth-of-type(3) > a.mw-lastlink',
            ],
          })
          .click();

        // Analyzing the page text to identify all the revision dates shown in the history list and determine which one is the oldest (earliest) revision.
        await page.ai.analyzePageText(
          'Extract all the revision dates from the history list and identify the oldest (earliest) date shown. The dates should be in "time, day month year format". List all dates found and identify which one is the earliest.',
          {
            additionalContext:
              'The page is currently showing the Software testing Wikipedia article\'s revision history sorted by oldest. I need to find the earliest revision date displayed on this page in the format "time, day month year".',
          },
        );

        // Scrolling down through the revision history list to find the oldest (earliest) revision, as the current view shows revisions from April 2004 down to January 2004, but I need to continue scrolling to find the very first revision.
        await page
          .find('#mw-history-search', {
            failover: [
              '#mw-history-searchform > fieldset',
              'fieldset.oo-ui-layout',
            ],
          })
          .scroll('DOWN', { maxScroll: true });

        // Scrolling down through the page to see more revisions in the history list and find the oldest (earliest) revision displayed.
        await page
          .find('html.client-js', { failover: ['html'] })
          .scroll('DOWN', { maxScroll: true });

        // Analyzing the page text to identify all revision dates shown in the current view and determine which one is the oldest (earliest) revision displayed on this page.
        await page.ai.analyzePageText(
          'Extract all the revision dates visible on this page in the format "time, day month year". List them in the order they appear and identify which one is the earliest (oldest) date.',
          {
            additionalContext:
              "The page is showing the Software testing Wikipedia article's revision history sorted by oldest. I can see revisions from December 2001. I need to identify the earliest date shown on this current view.",
          },
        );

        // I have successfully viewed the page history of the Software testing Wikipedia article, sorted by oldest, and identified the earliest (oldest) revision shown in the list.
        await page.run('markObjectiveComplete', {
          details:
            'The earliest (oldest) revision shown in the history list is: 13:57, 5 December 2001. This revision was made by user 166.46.99.xxx and is the first revision of the Software testing article on Wikipedia.',
        });
      },
    },
  ],
};
