/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'https://www.checklyhq.com/',
      instruction:
        'Click on the Resources dropdown menu, then click into to the developer docs option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the Resources dropdown menu to access the developer docs option as required by the overall objective.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
            {
              failover: [
                "(.//button[normalize-space(.)='Resources'])[1]",
                'nav.container > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
              ],
            },
          )
          .click();

        // Clicking on the Documentation link under the DEVELOPERS section to access the developer docs as required by the overall objective.
        await page
          .find(".//a[normalize-space(.)='Documentation']", {
            failover: [
              "li:nth-of-type(1) > [href='/docs/']",
              'div:nth-of-type(1) > ul > li:nth-of-type(1) > a.text-base',
            ],
          })
          .click();

        // The objective has been successfully completed. I clicked on the Resources dropdown menu on the Checkly homepage, which revealed the developer docs option. I then clicked on the "Documentation" link under the DEVELOPERS section, which navigated to the developer documentation page at https://www.checklyhq.com/docs/. The page now displays the Checkly Documentation with the title "Checkly Documentation" and shows various documentation sections including Getting Started, Detect, and Communicate sections.
        await page.run('markObjectiveComplete', {
          details:
            'Successfully navigated to the Checkly developer documentation by clicking on the Resources dropdown menu and then selecting the Documentation option. The current page is https://www.checklyhq.com/docs/ which displays the Checkly Documentation homepage with comprehensive developer resources.',
        });
      },
    },
    {
      pageUrl: 'https://www.checklyhq.com/docs/',
      instruction:
        'Do a search for "Playwright check suite" , after entring every word, check the search results and chose the match for "Constructs > DETECT". DONT submit the search.',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Opening the search bar to begin searching for "Playwright check suite" as required by the objective.
        await page
          .find('#search-bar-entry', {
            failover: [
              "div:nth-of-type(2) > [aria-label='Open search']",
              ".//button[normalize-space(.)='Search...⌘K']",
            ],
          })
          .click();

        // Typing the first word "Playwright" of the search query "Playwright check suite" to begin searching as required by the objective.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText('Playwright');

        // Continuing to type the second word "check" of the search query "Playwright check suite" to progress through the search as required by the objective.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText(' check', { append: true });

        // Typing the third and final word "suite" of the search query "Playwright check suite" to complete the search input as required by the objective.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText(' suite', { append: true });

        // Clicking on the search result that matches "Constructs > DETECT" to select it as required by the objective. This is the result showing "Constructs DETECT Playwright Check..." which is the match we need.
        await page
          .find(
            '#headlessui-dialog-_r_4_ > div:nth-of-type(2) > div > div:nth-of-type(2) > div:nth-of-type(2) > div > div',
            {
              failover: [
                'div:nth-of-type(2) > div:nth-of-type(2) > div > div.cursor-pointer',
                "[role='listbox'] > div:nth-of-type(2) > div > div",
              ],
            },
          )
          .click();

        // The objective has been successfully completed. I searched for "Playwright check suite" by entering each word sequentially (Playwright, then check, then suite), checked the search results after entering each word, and selected the match for "Constructs > DETECT" which was the "Playwright Check Suite" result under the DETECT section. The page has now navigated to the Playwright Check Suite documentation page at https://www.checklyhq.com/docs/constructs/playwright-check/, confirming that the correct result was selected. The search was not submitted as instructed.
        await page.run('markObjectiveComplete', {
          details:
            'Successfully completed the search for "Playwright check suite" and selected the "Constructs > DETECT" match. The browser is now on the Playwright Check Suite documentation page.',
        });
      },
    },
  ],
};
