/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Click on the Resources dropdown menu, then click into to the developer docs option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the 'Resources' dropdown menu to reveal more options, including 'Developer docs'.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
            {
              failover: [
                "(.//button[normalize-space(.)='Resources'])[1]",
                'nav.container > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
              ],
            },
          )
          .click('left');

        // Clicking on the 'Documentation' link within the 'Resources' dropdown menu, which corresponds to the 'developer docs' as specified in the objective.
        await page
          .find(".//a[normalize-space(.)='Documentation']", {
            failover: [
              "li:nth-of-type(1) > [href='/docs/']",
              'div:nth-of-type(1) > ul > li:nth-of-type(1) > a.text-base',
            ],
          })
          .click('left');

        // The objective to click the Resources dropdown and then the developer docs option has been met.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully navigated to the developer documentation by clicking the 'Resources' dropdown and then selecting the 'Documentation' option under the 'Developers' category. I am now at 'https://www.checklyhq.com/docs/'.",
        });
      },
    },
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Do a search for "Playwright check suite" , after entring every word, check the search results and chose the match for "Constructs > DETECT". DONT submit the search.',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Opening the search bar to begin the search for "Playwright check suite" as per the objective.
        await page
          .find('#search-bar-entry', {
            failover: [
              "div:nth-of-type(2) > [aria-label='Open search']",
              ".//button[normalize-space(.)='Search...⌘K']",
            ],
          })
          .click('left');

        // Entering the first word of the search query "Playwright" to begin looking for the specific documentation entry.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText('Playwright');

        // Appending the word " check" to the search query to refine the results as per the objective. I am checking the results after each word entered.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText(' check', { append: true });

        // Entering the final word " suite" of the search query "Playwright check suite" as instructed. I am checking the results after each word.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText(' suite', { append: true });

        // Choosing the match for "Constructs > DETECT" as per the objective, which is the "Playwright Check Suite" entry in the search results.
        await page
          .find(
            "[href='/docs/constructs/playwright-check#playwright-check-suite']",
            {
              failover: [
                'div:nth-of-type(2) > div > a.cursor-pointer',
                "[role='listbox'] > div:nth-of-type(2) > div > a",
              ],
            },
          )
          .click('left');

        // The objective has been completed as I followed the specific search steps and selected the requested result.
        await page.run('markObjectiveComplete', {
          details:
            'I successfully searched for "Playwright check suite" word by word without submitting the search. After entering the full query, I identified and clicked the match for "Constructs > DETECT > Playwright Check Suite" from the search results, which navigated me to the corresponding documentation page.',
        });
      },
    },
  ],
};
