/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Click on the Resources dropdown menu, then click into to the developer docs option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Closing the promotional modal to reveal the main navigation menu and access the 'Resources' dropdown.
        await page
          .find(".//button[normalize-space(.)='×']", {
            failover: [
              'html > body > div:nth-of-type(2) > div > div:nth-of-type(1) > button',
              'body > div:nth-of-type(2) > div > div:nth-of-type(1) > button',
            ],
          })
          .click('left');

        // Opening the 'Resources' dropdown menu to find the 'developer docs' option.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
            {
              failover: [
                "(.//button[normalize-space(.)='Resources'])[1]",
                'nav.container > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
              ],
            },
          )
          .click('left');

        // Clicking on the 'Documentation' link within the 'Resources' dropdown, which represents the developer docs.
        await page
          .find(".//a[normalize-space(.)='Documentation']", {
            failover: [
              "li:nth-of-type(1) > [href='/docs/']",
              'div:nth-of-type(1) > ul > li:nth-of-type(1) > a.text-base',
            ],
          })
          .click('left');

        // The objective was to click on the Resources dropdown and then the developer docs option. I have reached the Checkly Documentation page, which is the developer docs.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully navigated to the developer documentation by clicking on the 'Resources' dropdown menu and then selecting 'Documentation'. The browser is now at 'https://www.checklyhq.com/docs/'.",
        });
      },
    },
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Do a search for "Playwright check suite", and chose the match for "Constructs > DETECT" from the search suggestions dropdown.\n    NOTE: Since this website uses typeahead for search, do not submit the search via "Enter".',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the search bar to initiate the search for "Playwright check suite".
        await page
          .find('#search-bar-entry', {
            failover: [
              "div:nth-of-type(2) > [aria-label='Open search']",
              ".//button[normalize-space(.)='Search...⌘K']",
            ],
          })
          .click('left');

        // Typing the search query "Playwright check suite" to generate search suggestions. Enter is not pressed to allow for typeahead selection.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText('Playwright check suite');

        // Selecting the search suggestion for "Constructs > DETECT" as per the objective.
        await page
          .find(
            "[href='/docs/constructs/playwright-check#playwright-check-suite']",
            {
              failover: [
                'div:nth-of-type(2) > div > a.cursor-pointer',
                "[role='listbox'] > div:nth-of-type(2) > div > a",
              ],
            },
          )
          .click('left');

        // The objective has been met: the search was performed, and the specific suggestion "Constructs > DETECT" was chosen from the typeahead dropdown without submitting via Enter.
        await page.run('markObjectiveComplete', {
          details:
            'I searched for "Playwright check suite", and selected the "Constructs > DETECT" suggestion from the dropdown, which navigated to the "Playwright Check Suites" documentation page.',
        });
      },
    },
  ],
};
