/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'https://www.donobu.com/',
      instruction:
        'Scan the page for any responsiveness issues (overlap, misalignment, broken layout, clipping, bad spacing, resizing problems, or horizontal scroll). \n        Return PASS only if everything looks correct.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          status: { type: 'string', enum: ['PASS', 'FAIL'] },
          issues: { type: 'array', items: { type: 'string' } },
        },
        required: ['status', 'issues'],
        additionalProperties: false,
      },
      allowedTools: ['scroll', 'runAccessibilityTest'],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Running an accessibility test to help identify any responsiveness issues, layout problems, or other issues that might indicate broken responsive design on the current webpage.
        await page.runAccessibilityTest();

        // Scanning the page for responsiveness issues including overlap, misalignment, broken layout, clipping, bad spacing, resizing problems, or horizontal scroll. The current viewport shows the Donobu homepage with a clean, well-organized layout. The header contains a menu button (1), logo (0), and Download button (2) that are properly spaced and aligned. The main content area displays the headline "Local-First AI Testing for Every Team" with proper text alignment and spacing. The descriptive text is centered and readable. The "Download Donobu Studio" button (3) is prominently displayed and properly sized. The page appears to be scrollable vertically (as indicated by the scrollable DOWN property), which is appropriate for a single-page layout. All elements are properly positioned without overlap, clipping, or misalignment. The layout appears responsive and well-structured with no visible horizontal scroll or broken spacing issues.
        await page.run('markObjectiveComplete', {
          details:
            'PASS - The webpage displays correctly with no responsiveness issues detected. All elements are properly aligned, spaced, and positioned. No overlap, clipping, misalignment, broken layout, bad spacing, or horizontal scroll issues are present.',
        });
      },
    },
  ],
};
