/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.starbucks.com',
      instruction: 'Go to the featured menu page',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the "Order now" button to navigate to the featured menu page, as it points to the '/menu/featured/' URL.
        await page
          .find('#\\31 37-106044 > div > div > div:nth-of-type(2) > div > a', {
            failover: [
              '#primary-content > div:nth-of-type(2) > div > div > div > div:nth-of-type(2) > div > a',
              "(.//a[normalize-space(.)='Order now'])[1]",
            ],
          })
          .click();

        // The current URL is https://www.starbucks.com/menu/featured/, which confirms that the objective of reaching the featured menu page has been achieved.
        await page.run('markObjectiveComplete', {
          details:
            'I have navigated to the featured menu page at https://www.starbucks.com/menu/featured/.',
        });
      },
    },
    {
      pageUrl: 'www.starbucks.com',
      instruction: 'Find a Starbucks store in Stowe, Vermont',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am clicking 'Find a store' to access the store locator tool, which will allow me to search for Starbucks locations in Stowe, Vermont.
        await page
          .find("(.//a[normalize-space(.)='Find a store'])[1]", {
            failover: [
              "span:nth-of-type(1) > [href='/store-locator']",
              'span:nth-of-type(1) > a.sb-textLink',
            ],
          })
          .click();

        // I am typing 'Stowe, Vermont' into the store search field to find Starbucks locations in that specific area.
        await page
          .find(
            "[aria-label='Enter a location to search for Starbucks stores']",
            { failover: ["[name='place']", "[placeholder='Find a store']"] },
          )
          .inputText('Stowe, Vermont', { submit: true });

        // I have successfully located a Starbucks store in Stowe, Vermont, which satisfies the overall objective.
        await page.run('markObjectiveComplete', {
          details:
            "Found a Starbucks store in Stowe, Vermont: 'Stowe, 109 Main Street' located at 109 Main St, Stowe.",
        });
      },
    },
  ],
};
