/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'https://www.starbucks.com/',
      instruction: 'Go to the featured menu page',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Dismissing the cookie consent dialog by clicking the "Agree" button so I can proceed to navigate to the featured menu page
        await page
          .find('#truste-consent-button', {
            failover: [
              ".//button[normalize-space(.)='Agree']",
              'button.truste-button2',
            ],
          })
          .click();

        // Clicking on the MENU link in the navigation bar to navigate to the featured menu page
        await page
          .find("(.//a[normalize-space(.)='Menu'])[1]", {
            failover: [
              "div:nth-of-type(2) > div:nth-of-type(1) > ul > li:nth-of-type(1) > [href='/menu']",
              'li:nth-of-type(1) > a.sb-globalNav__desktopLink',
            ],
          })
          .click();

        // Clicking on the "Featured" link to navigate to the featured menu page as required by the objective
        await page
          .find(".//a[normalize-space(.)='Featured']", {
            failover: [
              "[href='https://www.starbucks.com/menu/featured']",
              'li:nth-of-type(2) > a.sb-global-subnav-item',
            ],
          })
          .click();

        // Successfully navigated to the featured menu page at https://www.starbucks.com/menu/featured/ which displays the featured items with the heading "Handcrafted joy to savor and share" and shows the Eggnog Latte as a featured item
        await page.run('markObjectiveComplete', {
          details:
            'The featured menu page has been successfully accessed. The page displays featured Starbucks items including the Eggnog Latte with its description. The URL confirms we are on the featured menu page: https://www.starbucks.com/menu/featured/',
        });
      },
    },
    {
      pageUrl: 'https://www.starbucks.com/menu/featured/',
      instruction: 'Find a Starbucks store in Stowe, Vermont',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the "Find a store" link to access the store locator feature so I can search for a Starbucks store in Stowe, Vermont.
        await page
          .find("(.//a[normalize-space(.)='Find a store'])[1]", {
            failover: [
              "span:nth-of-type(1) > [href='/store-locator']",
              'span:nth-of-type(1) > a.sb-textLink',
            ],
          })
          .click();

        // Entering "Stowe, Vermont" in the search field to find Starbucks stores in that location.
        await page
          .find(
            "[aria-label='Enter a location to search for Starbucks stores']",
            { failover: ["[name='place']", "[placeholder='Find a store']"] },
          )
          .inputText('Stowe, Vermont');

        // Clicking the submit search button to search for Starbucks stores in Stowe, Vermont.
        await page
          .find("[aria-label='Submit search term']", {
            failover: [
              "[data-e2e='submitSearchTermButton']",
              'button.button___s0b6x',
            ],
          })
          .click();

        // I have successfully found a Starbucks store in Stowe, Vermont. The search results clearly show "Stowe, 109 Main Street" located at 109 Main St, Stowe, which is 0.1 miles away and opens Thursday at 5:00 AM. This is the primary result displayed in the store locator.
        await page.run('markObjectiveComplete', {
          details:
            'Found Starbucks store: Stowe, 109 Main Street, located at 109 Main St, Stowe, Vermont. The store is 0.1 miles away from the search location and opens Thursday at 5:00 AM. It is currently closed but available for ordering.',
        });
      },
    },
  ],
};
