/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'unstable-survey-dinoer.replit.app',
      instruction:
        'Fill out the all of the survey questions with fake data go through\nthe submission process until you get to a "Thank You" page.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          surveyData: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                question: { type: 'string' },
                response: { type: 'string' },
              },
              required: ['question', 'response'],
              additionalProperties: false,
            },
          },
        },
        required: ['surveyData'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Filling in a fake name to progress through the survey.
        await page
          .find('#\\:rj\\:-form-item', {
            failover: [
              ".//label[normalize-space()='Your Name *']/following-sibling::input",
              "[name='name']",
            ],
          })
          .inputText('John Doe', { submit: true });

        // Providing a fake email address to continue with the survey.
        await page
          .find('#\\:rk\\:-form-item', {
            failover: [
              ".//label[normalize-space()='Contact Email *']/following-sibling::input",
              "[name='email']",
            ],
          })
          .inputRandomizedEmailAddress('johndoe@example.com', { submit: true });

        // Opening the occupation dropdown to select a fake occupation.
        await page
          .find('#\\:rl\\:-form-item', {
            failover: [
              ".//button[normalize-space(.)='Select your occupation']",
              "[role='combobox']",
            ],
          })
          .click('left');

        // Selecting 'Student' as the occupation to proceed with the survey.
        await page
          .find('#radix-\\:rm\\: > div > div:nth-of-type(1)', {
            failover: [
              ".//div[normalize-space(.)='Student']",
              "[data-highlighted='']",
            ],
          })
          .click('left');

        // Selecting 'Technology' as an interest to continue filling out the survey.
        await page
          .find('#\\:ro\\:-form-item', {
            failover: [
              "div:nth-of-type(1) > [role='checkbox']",
              "div:nth-of-type(1) > [data-state='unchecked']",
            ],
          })
          .click('left');

        // Scrolling down to find more survey questions or the submission button.
        await page.find('html').scroll('DOWN');

        // Clicking the 'Next' button to proceed to the next page of the survey.
        await page
          .find(".//button[normalize-space(.)='Next']", {
            failover: ['button.inline-flex', 'div.mt-8 > button'],
          })
          .click('left');

        // Clicking the 'Submit' button to finalize the survey submission and reach the 'Thank You' page.
        await page
          .find(".//button[normalize-space(.)='Submit']", {
            failover: [
              'div.mt-8 > button:nth-of-type(2)',
              'div.bg-white > div:nth-of-type(2) > button:nth-of-type(2)',
            ],
          })
          .click('left');

        // The 'Thank You' page has been reached, indicating the survey submission process is complete.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully filled out the survey with fake data and navigated through the submission process to reach the 'Thank You' page.",
        });
      },
    },
  ],
};
