/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'en.wikipedia.org',
      instruction:
        'View the page history, sort by oldest, and find the earliest (oldest) revision shown in the list (the history page displays in "time, day month year format").',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          day: { type: 'number' },
          month: { type: 'number' },
          year: { type: 'number' },
        },
        required: ['day', 'month', 'year'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking 'View history' to access the revision history of the 'Software testing' article.
        await page
          .find("(.//a[normalize-space(.)='View history'])[1]", {
            failover: [
              "[title='Past revisions of this page [ctrl-option-h]']",
              "nav:nth-of-type(1) > div > div > ul > li:nth-of-type(3) > [href='/w/index.php?title=Software_testing&action=history']",
            ],
          })
          .click();

        // Clicking 'oldest' to view the earliest revisions of the article.
        await page
          .find("(.//a[normalize-space(.)='oldest'])[1]", {
            failover: [
              "div:nth-of-type(3) > [href='/w/index.php?title=Software_testing&action=history&dir=prev']",
              'div:nth-of-type(3) > a.mw-lastlink',
            ],
          })
          .click();

        // Scrolling down to reach the bottom of the oldest revisions list to identify the very first revision.
        await page
          .find('html.client-js', { failover: ['html'] })
          .scroll('DOWN');

        // Scrolling to the very bottom of the page to ensure I have reached the end of the list of revisions.
        await page
          .find('html.client-js', { failover: ['html'] })
          .scroll('DOWN', { maxScroll: true });

        // I have navigated to the oldest revisions of the article and identified the final entry in the list, which corresponds to the very first revision.
        await page.run('markObjectiveComplete', {
          details:
            "The earliest (oldest) revision of the 'Software testing' article is 13:57, 5 December 2001.",
        });
      },
    },
  ],
};
