/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.saucedemo.com',
      instruction: 'Log in as a standard user',
      schema: null,
      allowedTools: [
        'analyzePageText',
        'assert',
        'assertPage',
        'changeWebBrowserTab',
        'chooseSelectOption',
        'click',
        'doubleClick',
        'goForwardOrBack',
        'goToWebpage',
        'handleBrowserDialog',
        'hoverOverElement',
        'inputRandomizedEmailAddress',
        'inputText',
        'makeComment',
        'markObjectiveComplete',
        'markObjectiveNotCompletable',
        'pressKey',
        'rememberPageText',
        'scrollPage',
        'setRunMode',
        'wait',
      ],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering the standard user username to proceed with the login process.
        await page
          .find("[data-test='username']", { failover: ["[name='user-name']"] })
          .inputText('standard_user');

        // Entering the password to complete the login process as a standard user.
        await page
          .find("[data-test='password']", { failover: ["[name='password']"] })
          .inputText('secret_sauce', { submit: true });

        // The user has successfully logged in as a standard user and is now on the inventory page, which confirms the objective is complete.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully logged in as 'standard_user' and redirected to the inventory page.",
        });
      },
    },
    {
      pageUrl: 'www.saucedemo.com',
      instruction: 'Log in as a standard user',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Inputting the standard username to begin the login process.
        await page
          .find("[data-test='username']", { failover: ["[name='user-name']"] })
          .inputText('standard_user');

        // Inputting the common password for all users and submitting to complete the login process.
        await page
          .find("[data-test='password']", { failover: ["[name='password']"] })
          .inputText('secret_sauce', { submit: true });

        // The user is now logged in and redirected to the inventory page, which satisfies the overall objective.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully logged in as 'standard_user' and am now on the inventory page.",
        });
      },
    },
  ],
};
