/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'www.saucedemo.com',
      instruction: 'Log in as a standard user',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering the username 'standard_user' into the username input field to log in.
        await page
          .find("[data-test='username']", {
            failover: ["[placeholder='Username']"],
          })
          .inputText('standard_user');

        // Entering the password 'secret_sauce' into the password input field.
        await page
          .find("[data-test='password']", { failover: ["[name='password']"] })
          .inputText('secret_sauce');

        // Clicking the Login button to submit the login credentials.
        await page
          .find("[data-test='login-button']", {
            failover: ["[name='login-button']"],
          })
          .click('left');

        // Verifying that the current page URL is the inventory page after logging in.
        await expect(page).toHaveURL(
          'https://www.saucedemo.com/inventory.html',
        );

        // Completing the objective as the login process for standard_user has succeeded and the inventory page is visible.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully logged in as 'standard_user' and navigated to the inventory page.",
        });
      },
    },
  ],
};
