/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'www.saucedemo.com',
      instruction: 'Checkout the cart',
      schema: null,
      allowedTools: [],
      maxToolCalls: 35,
      run: async ({ page }) => {
        // Clicking the checkout button to proceed with checking out the cart.
        await page
          .find("[data-test='checkout']", {
            failover: [".//button[normalize-space(.)='Checkout']"],
          })
          .click('left');

        // Entering first name in the checkout form.
        await page
          .find("[data-test='firstName']", {
            failover: ["[placeholder='First Name']"],
          })
          .inputText('John');

        // Entering last name in the checkout form.
        await page
          .find("[data-test='lastName']", { failover: ["[name='lastName']"] })
          .inputText('Doe');

        // Entering postal code in the checkout form.
        await page
          .find("[data-test='postalCode']", {
            failover: ["[placeholder='Zip/Postal Code']"],
          })
          .inputText('12345');

        // Clicking the Continue button to proceed to the checkout overview page.
        await page
          .find("[data-test='continue']", {
            failover: ["input[value='Continue']"],
          })
          .click('left');

        // Clicking the Finish button to complete the checkout process.
        await page
          .find("[data-test='finish']", {
            failover: [".//button[normalize-space(.)='Finish']"],
          })
          .click('left');

        // Marking the objective as complete since the cart has been checked out successfully.
        await page.run('markObjectiveComplete', {
          details:
            "The cart checkout process has been successfully completed, reaching the order confirmation page with the message 'Thank you for your order!'.",
        });
      },
    },
  ],
};
