/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.saucedemo.com',
      instruction: 'Checkout the cart',
      schema: null,
      allowedTools: [
        'analyzePageText',
        'assert',
        'changeWebBrowserTab',
        'chooseSelectOption',
        'click',
        'goForwardOrBack',
        'goToWebpage',
        'hoverOverElement',
        'inputRandomizedEmailAddress',
        'inputText',
        'makeComment',
        'markObjectiveComplete',
        'markObjectiveNotCompletable',
        'pressKey',
        'rememberPageText',
        'scrollPage',
        'wait',
      ],
      maxToolCalls: 35,
      run: async ({ page }) => {
        // Clicking the checkout button to proceed with the purchase.
        await page
          .find("[data-test='checkout']", {
            failover: [".//button[normalize-space(.)='Checkout']"],
          })
          .click('left');

        // Filling in the first name to complete the checkout information.
        await page
          .find("[data-test='firstName']", { failover: ["[name='firstName']"] })
          .inputText('John');

        // Entering the last name to proceed with the checkout information.
        await page
          .find("[data-test='lastName']", { failover: ["[name='lastName']"] })
          .inputText('Doe');

        // Entering the zip code to complete the checkout information.
        await page
          .find("[data-test='postalCode']", {
            failover: ["[name='postalCode']"],
          })
          .inputText('12345');

        // Clicking the continue button to proceed to the checkout overview page.
        await page
          .find("[data-test='continue']", { failover: ["[name='continue']"] })
          .click('left');

        // Clicking the 'Finish' button to complete the order.
        await page
          .find("[data-test='finish']", {
            failover: [".//button[normalize-space(.)='Finish']"],
          })
          .click('left');

        // The objective was to checkout the cart, and the screen now confirms 'Checkout: Complete!' with a thank you message.
        await page.run('markObjectiveComplete', {
          details:
            'The checkout process was completed successfully. Navigated through the cart, checkout information, and checkout overview steps to reach the order completion page.',
        });
      },
    },
    {
      pageUrl: 'www.saucedemo.com',
      instruction: 'Checkout the cart',
      schema: null,
      allowedTools: [],
      maxToolCalls: 35,
      run: async ({ page }) => {
        // Clicking the checkout button to proceed with the overall objective of checking out the cart.
        await page
          .find("[data-test='checkout']", {
            failover: [".//button[normalize-space(.)='Checkout']"],
          })
          .click('left');

        // Filling in the first name to proceed with the checkout process.
        await page
          .find("[data-test='firstName']", { failover: ["[name='firstName']"] })
          .inputText('John');

        // Entering the last name to complete the checkout information form.
        await page
          .find("[data-test='lastName']", { failover: ["[name='lastName']"] })
          .inputText('Doe');

        // Entering a zip code to complete the required checkout information.
        await page
          .find("[data-test='postalCode']", {
            failover: ["[name='postalCode']"],
          })
          .inputText('12345');

        // Clicking the 'Continue' button to move to the final checkout overview page.
        await page
          .find("[data-test='continue']", { failover: ["[name='continue']"] })
          .click('left');

        // Clicking the 'Finish' button to complete the checkout process and achieve the overall objective.
        await page
          .find("[data-test='finish']", {
            failover: [".//button[normalize-space(.)='Finish']"],
          })
          .click('left');

        // The overall objective was to checkout the cart. I have navigated through the checkout steps, entered the required information, and reached the final confirmation page.
        await page.run('markObjectiveComplete', {
          details:
            "The checkout process has been successfully completed, as indicated by the 'Checkout: Complete!' message and the 'Thank you for your order!' confirmation on the final page.",
        });
      },
    },
  ],
};
