/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Click on the Resources dropdown menu, then click into to the developer docs option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the Resources dropdown menu to reveal the developer docs option.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
            {
              failover: [
                "(.//button[normalize-space(.)='Resources'])[1]",
                'nav.container > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
              ],
            },
          )
          .click('left');

        // Clicking on 'Documentation' under the 'DEVELOPERS' heading, which serves as the developer docs.
        await page
          .find("(.//a[normalize-space(.)='Documentation'])[1]", {
            failover: [
              "li:nth-of-type(1) > [href='/docs/']",
              'div:nth-of-type(1) > ul > li:nth-of-type(1) > a.text-base',
            ],
          })
          .click('left');

        // The objective to click on the Resources dropdown and then click into the developer docs option has been fulfilled.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully clicked on the 'Resources' dropdown menu and then clicked on the 'Documentation' option, which led to the developer documentation page at https://www.checklyhq.com/docs/.",
        });
      },
    },
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Do a search for "Playwright check suite", and chose the match for "Constructs > DETECT" from the search suggestions dropdown.\n    NOTE: Since this website uses typeahead for search, do not submit the search via "Enter".',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the search bar to initiate the search for "Playwright check suite".
        await page
          .find('#search-bar-entry', {
            failover: [
              "div:nth-of-type(2) > [aria-label='Open search']",
              ".//button[normalize-space(.)='Search...⌘K']",
            ],
          })
          .click('left');

        // Typing "Playwright check suite" into the search bar to find relevant documentation matches. Not submitting via Enter to allow the typeahead suggestions to appear.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText('Playwright check suite');

        // Selecting the search suggestion for "Constructs > DETECT" as requested.
        await page
          .find(
            "[href='/docs/constructs/playwright-check#playwright-check-suite']",
            {
              failover: [
                'div:nth-of-type(2) > div > a.cursor-pointer',
                "[role='listbox'] > div:nth-of-type(2) > div > a",
              ],
            },
          )
          .click('left');

        // The objective has been met by searching for the specific term and selecting the required suggestion from the dropdown, which led to the correct documentation page.
        await page.run('markObjectiveComplete', {
          details:
            'I searched for "Playwright check suite" and selected the "Constructs > DETECT" suggestion. This navigated me to the "Playwright Check Suites" documentation page under the Constructs section.',
        });
      },
    },
  ],
};
