/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Click on the Resources dropdown menu, then click into to the developer docs option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the 'Resources' dropdown menu to reveal the developer docs option.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
            {
              failover: [
                "(.//button[normalize-space(.)='Resources'])[1]",
                'nav.container > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(2)',
              ],
            },
          )
          .click('left');

        // Clicking on the 'Documentation' link under the 'DEVELOPERS' section as it corresponds to the 'developer docs' option.
        await page
          .find("(.//a[normalize-space(.)='Documentation'])[1]", {
            failover: [
              "li:nth-of-type(1) > [href='/docs/']",
              'div:nth-of-type(1) > ul > li:nth-of-type(1) > a.text-base',
            ],
          })
          .click('left');

        // The objective was to navigate to the developer docs from the Resources dropdown menu. This has been achieved as the browser is now on the documentation page.
        await page.run('markObjectiveComplete', {
          details:
            "The 'Resources' dropdown menu was clicked, followed by the 'Documentation' link within the 'DEVELOPERS' section, leading to the Checkly Documentation page.",
        });
      },
    },
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Do a search for "Playwright check suite", and chose the match for "Constructs > DETECT" from the search suggestions dropdown.\n    NOTE: Since this website uses typeahead for search, do not submit the search via "Enter".',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking the search bar to initiate the search for "Playwright check suite" as per the objective.
        await page
          .find('#search-bar-entry', {
            failover: [
              "div:nth-of-type(2) > [aria-label='Open search']",
              ".//button[normalize-space(.)='Search...Ctrl K']",
            ],
          })
          .click('left');

        // Typing "Playwright check suite" into the search field to trigger the typeahead search suggestions, as instructed by the objective.
        await page
          .find('#search-input', {
            failover: ["[placeholder='Search...']", "[role='combobox']"],
          })
          .inputText('Playwright check suite');

        // Choosing the "Constructs > DETECT" match for "Playwright check suite" from the search suggestions dropdown as specified in the objective.
        await page
          .find(
            "[href='/docs/constructs/playwright-check#playwright-check-suite']",
            {
              failover: [
                'div:nth-of-type(2) > div > a.cursor-pointer',
                "[role='listbox'] > div:nth-of-type(2) > div > a",
              ],
            },
          )
          .click('left');

        // The objective has been fulfilled by navigating to the specific documentation page requested via the search suggestions.
        await page.run('markObjectiveComplete', {
          details:
            'I have successfully searched for "Playwright check suite" and selected the "Constructs > DETECT" match from the search suggestions, which led to the "Playwright Check Suites" documentation page.',
        });
      },
    },
  ],
};
