/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Click on the Developers dropdown menu, then click into to the Documentation option',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the Developers dropdown menu to open its options.
        await page
          .find("(.//button[normalize-space(.)='Developers'])[1]", {
            failover: [
              ".//button[normalize-space(.)='Developers']",
              'div:nth-of-type(3) > button.nav-item',
            ],
          })
          .click('left');

        // Hovering over the Developers dropdown menu to display its submenu options.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(3) > button',
            {
              failover: [
                "(.//button[normalize-space(.)='Developers'])[1]",
                'div:nth-of-type(3) > button.nav-item',
              ],
            },
          )
          .hover();

        // Clicking the Developers dropdown to open the menu.
        await page
          .find(
            '#nav > nav > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(3) > button',
            {
              failover: [
                "(.//button[normalize-space(.)='Developers'])[1]",
                'div:nth-of-type(3) > button.nav-item',
              ],
            },
          )
          .click('left');

        // Clicking on the Documentation option in the Developers dropdown menu.
        await page
          .find(
            "//div[@id='nav-dropdown-developers']//a[contains(., 'Documentation')]",
            {
              failover: [
                '#nav-dropdown-developers > div > div > div:nth-of-type(1) > div:nth-of-type(1) > a:nth-of-type(1)',
                "[href='/docs/']",
              ],
            },
          )
          .click('left');

        // The objective to click on the Developers dropdown menu and select Documentation has been successfully fulfilled.
        await page.run('markObjectiveComplete', {
          details:
            'Successfully clicked on the Developers dropdown menu and navigated to the Documentation option at https://www.checklyhq.com/docs/.',
        });
      },
    },
    {
      pageUrl: 'www.checklyhq.com',
      instruction:
        'Do a search for "Playwright check suite", and chose the match for "Constructs > DETECT" from the search suggestions dropdown.\n    NOTE: Since this website uses typeahead for search, do not submit the search via "Enter".',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the search bar to open the search dialog
        await page
          .find('#search-bar-entry', {
            failover: [
              ".//button[normalize-space(.)='Search...⌘K']",
              "div:nth-of-type(2) > [aria-label='Open search']",
            ],
          })
          .click('left');

        // Typing 'Playwright check suite' into the search input box without submitting with Enter
        await page
          .find('#search-input', {
            failover: [
              "[placeholder='Search or ask a question...']",
              "[data-component-part='search-input']",
            ],
          })
          .inputText('Playwright check suite');

        // Choosing the match for 'Constructs > DETECT' from the search suggestions dropdown
        await page
          .find(
            "[href='/docs/constructs/playwright-check#playwright-check-suite']",
            {
              failover: [
                "//a[@data-component-part='search-item'][contains(., 'Playwright Check Suite') and contains(., 'Constructs')]",
                ".//a[normalize-space(.)='Playwright Check SuiteConstructsDETECT']",
              ],
            },
          )
          .click('left');

        // The search and selection of the specified result from the suggestions dropdown has been completed.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully searched for 'Playwright check suite' without submitting via Enter and selected the 'Constructs > DETECT' option from the search suggestions dropdown, navigating to the Playwright Check Suites documentation under Constructs.",
        });
      },
    },
  ],
};
