/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'www.starbucks.com',
      instruction: 'Go to the "Rewards" page',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking the Rewards link in the navigation menu to go to the Rewards page.
        await page
          .find("a.sb-globalNav__desktopLink[href='/rewards']", {
            failover: [
              "nav[aria-label='Global'] a[href='/rewards']",
              ".//a[normalize-space(.)='Rewards']",
            ],
          })
          .click('left');

        // Confirming that the Rewards page has been successfully reached.
        await page.run('markObjectiveComplete', {
          details:
            'Successfully navigated to the Starbucks Rewards page (https://www.starbucks.com/rewards).',
        });
      },
    },
  ],
  assertions: [
    {
      pageUrl: 'www.starbucks.com',
      assertion: 'Ensure there is a CTA for joining the rewards program.',
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'Join now',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
  ],
};
