/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.starbucks.com',
      instruction: 'Go to the "Rewards" page',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking on the 'Rewards' link to navigate to the Rewards page as requested in the overall objective.
        await page
          .find("(.//a[normalize-space(.)='Rewards'])[1]", {
            failover: [
              "div:nth-of-type(2) > div:nth-of-type(1) > ul > li:nth-of-type(2) > [href='/rewards']",
              'li:nth-of-type(2) > a.sb-globalNav__desktopLink',
            ],
          })
          .click('left');

        // The overall objective was to go to the 'Rewards' page, and I am currently on that page.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully navigated to the Starbucks Rewards page, as evidenced by the current URL (https://www.starbucks.com/rewards) and the page content displaying 'Starbucks Rewards'.",
        });
      },
    },
  ],
};
