/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'unstable-survey-dinoer.replit.app',
      instruction:
        'Fill out the all of the survey questions with fake data go through\nthe submission process until you get to a "Thank You" page.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          surveyData: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                question: { type: 'string' },
                response: { type: 'string' },
              },
              required: ['question', 'response'],
              additionalProperties: false,
            },
          },
        },
        required: ['surveyData'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering a fake last name into the last name input field.
        await page
          .find("[data-testid='input-lastname']", {
            failover: [
              "[placeholder='Enter your last name']",
              ".//label[normalize-space()='Last Name *']/following-sibling::input",
            ],
          })
          .inputText('Smith');

        // Entering a fake email address into the email input field.
        await page
          .find(
            ".//label[normalize-space()='Email Address *']/following-sibling::input",
            {
              failover: [
                "[name='email']",
                "[placeholder='Enter your email address']",
              ],
            },
          )
          .inputText('john.smith@example.com');

        // Selecting an age group option.
        await page
          .find("[data-testid='radio-age-25-34']", {
            failover: [
              "button[role='radio'][value='25-34']",
              "div:nth-of-type(2) > [role='radio']",
            ],
          })
          .click('left');

        // Scrolling down to view more survey fields.
        await page.find('html').scroll('DOWN');

        // Selecting the 'Social Media' checkbox for 'How did you hear about us?'.
        await page
          .find(
            "//label[contains(text(), 'Social Media')]/parent::div//button[@role='checkbox']",
            {
              failover: [
                "//button[@role='checkbox' and following-sibling::label[contains(text(), 'Social Media')]]",
                "div:nth-of-type(1) > [role='checkbox']",
              ],
            },
          )
          .click('left');

        // Scrolling up to verify all required fields on the first page of the survey are completed.
        await page.find('html').scroll('UP', { maxScroll: true });

        // Scrolling down to locate and click the Next button.
        await page.find('html').scroll('DOWN');

        // Clicking the Next button to proceed to the next step of the survey.
        await page
          .find(".//button[normalize-space(.)='Next']", {
            failover: ['button[type="submit"]', 'div.mt-8 > button'],
          })
          .click('left');

        // Clicking the Submit button to finalize the survey submission.
        await page
          .find(".//button[normalize-space(.)='Submit']", {
            failover: [
              'div.mt-8 > button:nth-of-type(2)',
              'div.bg-white > div:nth-of-type(2) > button:nth-of-type(2)',
            ],
          })
          .click('left');

        // Marking the objective complete as the survey submission has been finished and the Thank You page is reached.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully filled out all survey questions with fake data, reviewed selections, submitted the survey, and reached the 'Thank You' page.",
        });
      },
    },
  ],
};
