/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'unstable-survey-dinoer.replit.app',
      instruction:
        'Fill out the all of the survey questions with fake data go through\nthe submission process until you get to a "Thank You" page.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          surveyData: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                question: { type: 'string' },
                response: { type: 'string' },
              },
              required: ['question', 'response'],
              additionalProperties: false,
            },
          },
        },
        required: ['surveyData'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering a fake last name to progress through the survey.
        await page
          .find('#\\:r0\\:-form-item', {
            failover: [
              "[data-testid='input-lastname']",
              ".//label[normalize-space()='Last Name *']/following-sibling::input",
            ],
          })
          .inputText('Doe');

        // Entering a fake email address to progress through the survey.
        await page
          .find('#\\:r1\\:-form-item', {
            failover: [
              ".//label[normalize-space()='Email Address *']/following-sibling::input",
              "[name='email']",
            ],
          })
          .inputRandomizedEmailAddress('fakeuser@example.com');

        // Selecting an age group as part of filling out the survey.
        await page
          .find('#\\:r5\\:-form-item', {
            failover: [
              "[data-testid='radio-age-25-34']",
              "div:nth-of-type(2) > [role='radio']",
            ],
          })
          .click('left');

        // Scrolling down to find more survey questions and the 'Next' button.
        await page.find('html').scroll('DOWN');

        // Selecting 'Search Engine' for the question 'How did you hear about us?' to complete the survey requirements.
        await page
          .find('#\\:rf\\:-form-item', {
            failover: [
              "div:nth-of-type(2) > [role='checkbox']",
              "div:nth-of-type(2) > [data-state='unchecked']",
            ],
          })
          .click('left');

        // Entering fake additional comments to complete the survey form.
        await page
          .find('#\\:ri\\:-form-item', {
            failover: [
              ".//label[normalize-space()='Additional Comments (Optional)']/following-sibling::textarea",
              "[name='comments']",
            ],
          })
          .inputText('This is a great survey experience!');

        // Clicking 'Next' to proceed to the next step of the survey.
        await page
          .find(".//button[normalize-space(.)='Next']", {
            failover: ['button.inline-flex', 'div.mt-8 > button'],
          })
          .click('left');

        // Clicking the 'Submit' button to finalize the survey submission and reach the 'Thank You' page.
        await page
          .find(".//button[normalize-space(.)='Submit']", {
            failover: [
              'div.mt-8 > button:nth-of-type(2)',
              'div.bg-white > div:nth-of-type(2) > button:nth-of-type(2)',
            ],
          })
          .click('left');

        // The objective was to fill out the survey and reach the 'Thank You' page, which has been achieved.
        await page.run('markObjectiveComplete', {
          details:
            "I have successfully filled out the survey with fake data, gone through the review process, and reached the 'Thank You' page as requested.",
        });
      },
    },
  ],
};
