/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'unstable-survey-dinoer.replit.app',
      instruction:
        'Fill out the all of the survey questions with fake data go through\nthe submission process until you get to a "Thank You" page.',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          surveyData: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                question: { type: 'string' },
                response: { type: 'string' },
              },
              required: ['question', 'response'],
              additionalProperties: false,
            },
          },
        },
        required: ['surveyData'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering a fake last name to start filling out the survey form.
        await page
          .find("[data-testid='input-lastname']", {
            failover: [
              ".//label[normalize-space()='Last Name *']/following-sibling::input",
              "[name='name']",
            ],
          })
          .inputFaker('person.lastName');

        // Entering a fake email address to satisfy the required field.
        await page
          .find(
            ".//label[normalize-space()='Email Address *']/following-sibling::input",
            {
              failover: [
                "[name='email']",
                "[placeholder='Enter your email address']",
              ],
            },
          )
          .inputFaker('internet.email');

        // Selecting an age group (25-34) from the radio button options.
        await page
          .find("[data-testid='radio-age-25-34']", {
            failover: [
              "div:nth-of-type(2) > [role='radio']",
              "div:nth-of-type(2) > [data-radix-collection-item='']",
            ],
          })
          .click('left');

        // Scrolling down to see the remaining survey questions on the page.
        await page.find('html').scroll('DOWN', { maxScroll: true });

        // Selecting 'Social Media' under 'How did you hear about us?'.
        await page
          .find("div:nth-of-type(1) > [role='checkbox']", {
            failover: [
              "div:nth-of-type(2) > div:nth-of-type(1) > [data-state='unchecked']",
              'div:nth-of-type(1) > button.peer',
            ],
          })
          .click('left');

        // Clicking the 'Next' button to submit this step of the survey.
        await page
          .find(".//button[normalize-space(.)='Next']", {
            failover: ['button.inline-flex', 'div.mt-8 > button'],
          })
          .click('left');

        // Clicking the 'Submit' button to complete the survey and reach the 'Thank You' page.
        await page
          .find(".//button[normalize-space(.)='Submit']", {
            failover: [
              'div.mt-8 > button:nth-of-type(2)',
              'div.bg-white > div:nth-of-type(2) > button:nth-of-type(2)',
            ],
          })
          .click('left');

        // The survey has been successfully submitted and the 'Thank You' page is displayed, matching our overall objective.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully completed all survey steps with fake data and reached the 'Thank You' confirmation page.",
        });
      },
    },
  ],
};
