/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'www.virvly.com',
      instruction:
        'Click the "Send Message" button without filling in any field of the contact form',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Scrolling down the page to locate the Send Message button in the contact form.
        await page
          .find('html.scroll-smooth', { failover: ['html'] })
          .scroll('DOWN');

        // Clicking the "Send Message" button without filling in any field of the contact form as requested by the objective.
        await page
          .find('#contact-form button[type="submit"]', {
            failover: [
              "//button[contains(., 'Send Message')]",
              ".//button[normalize-space(.)='Send Message →']",
            ],
          })
          .click('left');

        // Marking the objective complete as the Send Message button has been clicked without filling in any fields.
        await page.run('markObjectiveComplete', {
          details:
            "Clicked the 'Send Message' button on the contact form without filling in any input fields.",
        });
      },
    },
    {
      pageUrl: 'www.virvly.com',
      instruction:
        'Fill in the contact form with the name "Alex Mercer", the email address "alex@example" and the message "Do you cover weddings?", then click "Send Message"',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Inputting the name "Alex Mercer" into the name field of the contact form.
        await page
          .find('#contact-name', {
            failover: [
              ".//label[normalize-space()='Your Name']/following-sibling::input",
              "[name='name']",
            ],
          })
          .inputText('Alex Mercer');

        // Scrolling down to view the rest of the contact form fields.
        await page
          .find('html.scroll-smooth', { failover: ['html'] })
          .scroll('DOWN');

        // Inputting the email "alex@example" into the email address field.
        await page
          .find('#contact-email', {
            failover: [
              ".//label[normalize-space()='Email Address']/following-sibling::input",
              "[name='email']",
            ],
          })
          .inputText('alex@example');

        // Inputting the message "Do you cover weddings?" into the message textarea.
        await page
          .find('#contact-message', {
            failover: [
              ".//label[normalize-space()='Your Message']/following-sibling::textarea",
              "[name='message']",
            ],
          })
          .inputText('Do you cover weddings?');

        // Clicking the "Send Message" button to submit the contact form.
        await page
          .find('#contact-form button[type="submit"]', {
            failover: [
              "//button[contains(., 'Send Message')]",
              ".//button[normalize-space(.)='Send Message →']",
            ],
          })
          .click('left');

        // The contact form has been filled with the requested values and the Send Message button has been clicked.
        await page.run('markObjectiveComplete', {
          details:
            "Filled in the contact form with the name 'Alex Mercer', the email address 'alex@example', the message 'Do you cover weddings?', and clicked the 'Send Message' button.",
        });
      },
    },
    {
      pageUrl: 'www.virvly.com',
      instruction:
        'Fill in the contact form with the name "Alex Mercer", the email address "alex@example.com" and the message "Do you cover weddings?", then click "Send Message"',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering the name Alex Mercer into the name input field.
        await page
          .find('#contact-name', {
            failover: [
              ".//label[normalize-space()='Your Name']/following-sibling::input",
              "[name='name']",
            ],
          })
          .inputText('Alex Mercer');

        // Scrolling down to view the rest of the contact form.
        await page
          .find('html.scroll-smooth', { failover: ['html'] })
          .scroll('DOWN');

        // Entering the email address alex@example.com into the email input field.
        await page
          .find('#contact-email', {
            failover: [
              ".//label[normalize-space()='Email Address']/following-sibling::input",
              "[name='email']",
            ],
          })
          .inputText('alex@example.com');

        // Entering the message 'Do you cover weddings?' into the message textarea.
        await page
          .find('#contact-message', {
            failover: [
              ".//label[normalize-space()='Your Message']/following-sibling::textarea",
              "[name='message']",
            ],
          })
          .inputText('Do you cover weddings?');

        // Clicking the 'Send Message' button to submit the contact form.
        await page
          .find('#contact-form button[type="submit"]', {
            failover: [
              "//button[contains(., 'Send Message')]",
              ".//button[normalize-space(.)='Send Message →']",
            ],
          })
          .click('left');

        // The objective has been completed successfully as the form was submitted and confirmed.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully filled in the contact form with the name 'Alex Mercer', email 'alex@example.com', and message 'Do you cover weddings?', and clicked 'Send Message'. The message sent confirmation screen is now displayed.",
        });
      },
    },
    {
      pageUrl: 'www.virvly.com',
      instruction:
        'Fill in the contact form with the name "Alex Mercer", the email address "alex@example.com" and the message "Do you cover weddings?", then click "Send Message" exactly once. The send is expected to fail; do not retry, reload, or change anything afterwards.',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Entering the name 'Alex Mercer' into the contact form name input field.
        await page
          .find('#contact-name', {
            failover: [
              ".//label[normalize-space()='Your Name']/following-sibling::input",
              "[name='name']",
            ],
          })
          .inputText('Alex Mercer');

        // Scrolling down to reveal the email, message, and submit button in the contact form.
        await page
          .find('html.scroll-smooth', { failover: ['html'] })
          .scroll('DOWN');

        // Entering the email address 'alex@example.com' into the contact form email input field.
        await page
          .find('#contact-email', {
            failover: [
              ".//label[normalize-space()='Email Address']/following-sibling::input",
              "[name='email']",
            ],
          })
          .inputText('alex@example.com');

        // Entering the message 'Do you cover weddings?' into the contact message textarea.
        await page
          .find('#contact-message', {
            failover: [
              ".//label[normalize-space()='Your Message']/following-sibling::textarea",
              "[name='message']",
            ],
          })
          .inputText('Do you cover weddings?');

        // Clicking 'Send Message' button exactly once as requested in the objective.
        await page
          .find('#contact-form button[type="submit"]', {
            failover: [
              "//button[contains(., 'Send Message')]",
              ".//button[normalize-space(.)='Send Message →']",
            ],
          })
          .click('left');

        // The objective instructions have been fully followed: filled form, clicked Send Message once, expected failure occurred, and no retries/reloads were done.
        await page.run('markObjectiveComplete', {
          details:
            "Filled in the contact form with name 'Alex Mercer', email 'alex@example.com', and message 'Do you cover weddings?', clicked 'Send Message' once, and observed the expected failure message 'Mail service unavailable'. Objective complete.",
        });
      },
    },
  ],
  assertions: [
    {
      pageUrl: 'www.virvly.com',
      assertion:
        'The region contains a name field, an email address field, a message field, and a "Send Message" button.',
      scope: ['selector:#contact-form'],
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'YOUR NAME',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
        {
          locator: 'text',
          role: null,
          value: 'EMAIL ADDRESS',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
        {
          locator: 'text',
          role: null,
          value: 'YOUR MESSAGE',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
        {
          locator: 'role',
          role: 'button',
          value: 'Send Message.*',
          valueIsRegex: true,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
    {
      pageUrl: 'www.virvly.com',
      assertion:
        'The page promises a response within 24 hours and lists hello@virvly.com as the contact email.',
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'hello@virvly.com',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
        {
          locator: 'text',
          role: null,
          value: 'Guaranteed within 24 hours, Monday to Sunday.',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
    {
      pageUrl: 'www.virvly.com',
      assertion: 'An error message says the email address is not valid.',
      scope: ['selector:#contact-form'],
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'Please enter a valid email address.',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
    {
      pageUrl: 'www.virvly.com',
      assertion: 'The region confirms that the message was sent.',
      scope: ['selector:#success-card'],
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'Message Sent!',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
  ],
  locators: [
    {
      pageUrl: 'www.virvly.com',
      description:
        'The hello@virvly.com link in the "General & Business Email" card',
      result: {
        frames: [],
        steps: [
          {
            method: 'getByRole',
            role: 'link',
            name: 'hello@virvly.com',
            text: '',
            testId: '',
            selector: '',
            exact: true,
            nameIsRegex: false,
            textIsRegex: false,
          },
        ],
        nth: 0,
      },
    },
  ],
};
