/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'en.wikipedia.org',
      instruction:
        'Search for "Playwright (software)" and open the article about the Playwright testing framework',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Typing 'Playwright (software)' into the Wikipedia search box and pressing Enter to search for the article.
        await page
          .find('#searchInput', {
            failover: [
              '#searchform > div > div > input',
              "[aria-label='Search Wikipedia']",
            ],
          })
          .inputText('Playwright (software)', { submit: true });

        // Verifying that the current page title is 'Playwright (software) - Wikipedia'.
        await expect(page).toHaveTitle('Playwright (software) - Wikipedia');

        // The objective to search for 'Playwright (software)' and open the article about the Playwright testing framework has been accomplished.
        await page.run('markObjectiveComplete', {
          details:
            "Successfully searched for 'Playwright (software)' on Wikipedia and navigated to the article about the Playwright testing framework.",
        });
      },
    },
  ],
  assertions: [
    {
      pageUrl: 'en.wikipedia.org',
      assertion: 'The article heading names Playwright',
      steps: [
        {
          locator: 'role',
          role: 'heading',
          value: 'Playwright (software)',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
    {
      pageUrl: 'en.wikipedia.org',
      assertion: 'The "Written in" row lists TypeScript',
      scope: ['description:the infobox at the top right of the article'],
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'Written in',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
        {
          locator: 'role',
          role: 'link',
          value: 'TypeScript',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
  ],
  locators: [
    {
      pageUrl: 'en.wikipedia.org',
      description: 'the infobox at the top right of the article',
      result: {
        frames: [],
        steps: [
          {
            method: 'getByRole',
            role: 'table',
            name: '',
            text: '',
            testId: '',
            selector: '',
            exact: false,
            nameIsRegex: false,
            textIsRegex: false,
          },
        ],
        nth: 0,
      },
    },
  ],
};
