/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'en.wikipedia.org',
      instruction:
        'View the page history, sort by oldest, and find the earliest (oldest) revision shown in the list (the history page displays in "time, day month year format").',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          day: { type: 'number' },
          month: { type: 'number' },
          year: { type: 'number' },
        },
        required: ['day', 'month', 'year'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Clicking the View history button to navigate to the page revision history.
        await page
          .find('#ca-history > a', {
            failover: [
              "(.//a[normalize-space(.)='View history'])[1]",
              "nav:nth-of-type(1) > div > div > ul > li:nth-of-type(3) > [title='Past revisions of this page [ctrl-option-h]']",
            ],
          })
          .click('left');

        // Clicking the 'oldest' link to sort/view the revisions from the oldest.
        await page
          .find("(.//a[normalize-space(.)='oldest'])[1]", {
            failover: ['a.mw-lastlink', ".//a[normalize-space(.)='oldest']"],
          })
          .click('left');

        // Scrolling down to the bottom of the page to find the earliest (oldest) revision in the list.
        await page
          .find('html.client-js', { failover: ['html'] })
          .scroll('DOWN', { maxScroll: true });

        // Marking the objective as complete since we navigated to page history, sorted by oldest, and found the earliest revision date/time.
        await page.run('markObjectiveComplete', {
          details:
            'The earliest (oldest) revision shown in the list is 13:57, 5 December 2001.',
        });
      },
    },
  ],
};
