/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('@donobu/test');

module.exports = {
  caches: [
    {
      pageUrl: 'news.ycombinator.com',
      instruction:
        'Scroll to the bottom of the page, locate search input field, do a search with keyword "mac app for web testing"',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Scrolling to the bottom of the Hacker News page to locate the search input field.
        await page
          .find('html > body', { failover: ['body'] })
          .scroll('DOWN', { maxScroll: true });

        // Inputting the search query 'mac app for web testing' into the search input field and submitting.
        await page
          .find(
            '#hnmain > tbody > tr:nth-of-type(4) > td > center > form > input',
            { failover: ["[name='q']", 'form > input'] },
          )
          .inputText('mac app for web testing', { submit: true });

        // The objective to scroll to the bottom of the page, locate the search input field, and search for 'mac app for web testing' has been completed.
        await page.run('markObjectiveComplete', {
          details:
            "Scrolled to the bottom of Hacker News, found the search input field, and successfully performed a search for 'mac app for web testing'. The search results page on Algolia is now displayed.",
        });
      },
    },
  ],
  assertions: [
    {
      pageUrl: 'hn.algolia.com',
      assertion: 'Donobu appears among the top search results',
      steps: [
        {
          locator: 'text',
          role: null,
          value: 'Show HN: Donobu – Mac App for Web Automation and Testing',
          valueIsRegex: false,
          assertion: 'toBeVisible',
          attributeValue: null,
        },
      ],
    },
  ],
};
