/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'news.ycombinator.com',
      instruction:
        'Scroll to the bottom of the page, locate search input field, do a search with keyword "mac app for web testing"',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Scrolling to the bottom of the page to locate the search input field as per the objective.
        await page
          .find('html > body', { failover: ['body'] })
          .scroll('DOWN', { maxScroll: true });

        // Inputting the search keyword "mac app for web testing" into the search field and submitting the search.
        await page
          .find(
            '#hnmain > tbody > tr:nth-of-type(4) > td > center > form > input',
            { failover: ["[name='q']", 'form > input'] },
          )
          .inputText('mac app for web testing', { submit: true });

        // The search has been completed and the results page is visible.
        await page.run('markObjectiveComplete', {
          details:
            'I have successfully scrolled to the bottom of the page, located the search input field, and performed a search with the keyword "mac app for web testing". The search results are now displayed.',
        });
      },
    },
  ],
};
