name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * *" # Runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.0-jammy

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Ensure test-results directory exists
        run: mkdir -p test-results

      - name: Run Playwright tests
        id: run_tests
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npx playwright test

      - name: Upload JUnit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: test-results/results.xml
          retention-days: 7

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 7
