name: Run Donobu Flows

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * *" # Runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  run-donobu-flows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install && npx playwright install --with-deps

      - name: Run Playwright tests
        id: run_tests
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SELF_HEAL_TESTS_ENABLED: true
        run: npx playwright test

      - name: Automatically create a pull request for fixing failed tests (if any)
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fix failing Playwright tests"
          title: "[Fixed] Playwright tests"
          body: "Fix failing Playwright tests"
          branch: fix-playwright-tests
          base: main
